"""QP implementation of the paper's combinatorial reach-avoid filter.

The Hamilton-Jacobi part contains p+1 inequalities:

1. One inequality keeps the selected target reachable on the shrinking active
   horizon tau_1.
2. One inequality per target preserves the r-out-of-p pivot set on the
   contingency horizon tau_2.

A Poisson CBF inequality generated by ``cbf_safety_box`` is appended to the same
QP, so local geometric safety and landing contingency are enforced jointly.
"""
from __future__ import annotations

from dataclasses import dataclass
import time

import numpy as np
from scipy.optimize import Bounds, minimize

from .hj_reachability import rth_largest


@dataclass
class UnifiedQPResult:
    u_safe: np.ndarray
    omega_active: float
    omega_contingency: float
    success: bool
    status: str
    solve_time_s: float
    poisson_residual: float
    active_hj_residual: float
    contingency_residuals: np.ndarray
    pivot_value: float
    reachable_count: int


def solve_unified_qp(
    u_nom: np.ndarray,
    poisson_A: np.ndarray,
    poisson_b: np.ndarray,
    active_sample: dict,
    contingency_samples: list[dict],
    required_reachable: int,
    tau1_dot: float,
    tau2_dot: float,
    max_speed: float,
    alpha_active: float,
    alpha_contingency: float,
    rho_gain: float,
    omega_weight: float,
    max_omega: float,
) -> UnifiedQPResult:
    """Solve the joint velocity QP in variables [u_x,u_y,u_z,omega_1,omega_2]."""
    start = time.perf_counter()
    u_nom = np.asarray(u_nom, dtype=float).reshape(3)
    A_p = np.asarray(poisson_A, dtype=float).reshape(-1, 3)
    b_p = np.asarray(poisson_b, dtype=float).reshape(-1)
    values = np.array([sample["V"] for sample in contingency_samples], dtype=float)
    pivot = rth_largest(values, required_reachable)
    reachable_count = int(np.count_nonzero(values >= 0.0))

    # Paper terms.  rho(s)=rho_gain*s^2 is positive definite and vanishes only
    # at the critical r-th value, which is the non-relaxable pivot constraint.
    rho = np.array([rho_gain * (sample["V"] - pivot) ** 2 for sample in contingency_samples], dtype=float)
    active_relax_coeff = max(0.0, -alpha_active * float(active_sample["V"]))

    def objective(z: np.ndarray) -> float:
        du = z[:3] - u_nom
        return 0.5 * float(du @ du) + omega_weight * float(z[3] ** 2 + z[4] ** 2)

    def objective_jac(z: np.ndarray) -> np.ndarray:
        grad = np.zeros(5, dtype=float)
        grad[:3] = z[:3] - u_nom
        grad[3] = 2.0 * omega_weight * z[3]
        grad[4] = 2.0 * omega_weight * z[4]
        return grad

    def inequality_values(z: np.ndarray) -> np.ndarray:
        u = z[:3]
        omega1, omega2 = z[3], z[4]
        residuals: list[float] = []
        # Poisson CBF constraint obtained from CBF Safety Box: A_p u >= b_p.
        residuals.extend((A_p @ u - b_p).tolist())
        # Active target condition from Eq. (21).
        active_dot = float(active_sample["grad_V"] @ u + active_sample["partial_tau"] * tau1_dot)
        residuals.append(active_dot + alpha_active * float(active_sample["V"]) + omega1 * active_relax_coeff)
        # p combinatorial reachability constraints from Eq. (21).
        for j, sample in enumerate(contingency_samples):
            vdot = float(sample["grad_V"] @ u + sample["partial_tau"] * tau2_dot)
            residuals.append(vdot + alpha_contingency * float(sample["V"]) + omega2 * rho[j])
        # Euclidean velocity-ball constraint.
        residuals.append(float(max_speed**2 - u @ u))
        return np.asarray(residuals, dtype=float)

    u0 = u_nom.copy()
    norm = float(np.linalg.norm(u0))
    if norm > max_speed:
        u0 *= max_speed / norm
    z0 = np.concatenate([u0, [0.0, 0.0]])
    bounds = Bounds(
        lb=np.array([-max_speed, -max_speed, -max_speed, 0.0, 0.0]),
        ub=np.array([max_speed, max_speed, max_speed, max_omega, max_omega]),
    )
    result = minimize(
        objective,
        z0,
        jac=objective_jac,
        method="SLSQP",
        bounds=bounds,
        constraints=[{"type": "ineq", "fun": inequality_values}],
        options={"ftol": 1e-9, "maxiter": 120, "disp": False},
    )
    z = np.asarray(result.x, dtype=float)
    u_safe = z[:3]
    all_residuals = inequality_values(z)
    n_poisson = A_p.shape[0]
    poisson_residual = float(np.min(all_residuals[:n_poisson])) if n_poisson else np.inf
    active_residual = float(all_residuals[n_poisson])
    contingency_residuals = all_residuals[n_poisson + 1 : n_poisson + 1 + len(contingency_samples)]
    success = bool(result.success and np.min(all_residuals) >= -2e-5)

    # Fail-safe: a zero velocity is preferable to returning an invalid command.
    # The result remains marked unsuccessful so the plot and CSV expose it.
    if not np.all(np.isfinite(u_safe)):
        u_safe = np.zeros(3, dtype=float)
        success = False

    return UnifiedQPResult(
        u_safe=u_safe,
        omega_active=float(z[3]),
        omega_contingency=float(z[4]),
        success=success,
        status=str(result.message),
        solve_time_s=time.perf_counter() - start,
        poisson_residual=poisson_residual,
        active_hj_residual=active_residual,
        contingency_residuals=np.asarray(contingency_residuals, dtype=float),
        pivot_value=pivot,
        reachable_count=reachable_count,
    )
