"""Public interface for the modular CBF Safety Box.

The package accepts safety samples generated by another module, most notably
``poisson_safety_box``, and converts nominal commands into safe commands through
CBF/HOCBF and contingency-aware quadratic programs.
"""

from .api import CBFBox
from .config import CBFBoxConfig, BacksteppingConfig, DiagnosticsConfig, PlottingConfig
from .state import SystemState
from .result import CBFBoxResult
from .safety_data.sample import SafetySample
from .constraints import (
    Constraint,
    AffineCertificate,
    build_acceleration_hocbf_constraint,
    build_active_target_clf_constraint,
    build_active_target_reachability_constraint,
    build_combinatorial_contingency_constraints,
    lift_constraint_with_auxiliary,
    lift_constraint_to_decision,
    rth_largest_pivot,
)

__all__ = [
    "CBFBox",
    "CBFBoxConfig",
    "BacksteppingConfig",
    "DiagnosticsConfig",
    "PlottingConfig",
    "SystemState",
    "SafetySample",
    "CBFBoxResult",
    "Constraint",
    "AffineCertificate",
    "build_acceleration_hocbf_constraint",
    "build_active_target_clf_constraint",
    "build_active_target_reachability_constraint",
    "build_combinatorial_contingency_constraints",
    "lift_constraint_with_auxiliary",
    "lift_constraint_to_decision",
    "rth_largest_pivot",
]
